### ISSUE TITLE
Changing placeholder and disabling replies

### ISSUE THREAD

**Issue by hounsellal** [recogito/recogito-client-core#110]
Is there a way with the comment widget to change the placeholder and disable replies?

E.g.:

var r = Recogito.init({
                  content: document.getElementById('my-content'),
                  widgets: [{widget: "COMMENT", placeholder: "Add an optional note", allowReplies: false}],
                  allowEmpty: true,
                  mode: 'pre' 
                });

**Comment by rsimon** [comment]
You can change the placeholder by overriding the localization labels, using the `messages` property. (I18n is a global thing, i.e. this is a prop at the top level of the config object, not in the widget config.) See here:

https://recogito.github.io/annotorious/api-docs/annotorious/

and here:

https://recogito.github.io/guides/contributing-ui-translations/

I.e. you'd need a replacement 

```json
{ 'Add a comment': 'My placeholder' }
```

Disabling the reply is currently not possible in afraid. But people have been hiding it with CSS I think.
