### ISSUE TITLE
[Widgets/Comment] hasOwnProperty check fails on null proto objects

### ISSUE THREAD

**Issue by brendan-lee** [recogito/recogito-client-core#115]
I'm using Annotorious OpenSeadragon 2.7.10.

In my use case, annotations are saved in the database in JSON format. When displayed on the front end, the JSON strings are parsed back into an array and then loaded into Annotorious using the `setAnnotations` method.

For some reason, I'm using the [json-bigint](https://www.npmjs.com/package/json-bigint) library instead of the native `JSON.parse`. To avoid prototype pollution, this lib sets the prototype of all objects to `null` when parsing.

Annotorious loads these annotations correctly. However, when clicking on an annotation, the console throws an error: "hasOwnProperty is not a function".

The reason is the direct use of the `hasOwnProperty` method on the annotation object's prototype. To fix it, `Object.prototype.hasOwnProperty` should be used.

Here's a reproduction demo:

https://codepen.io/lzm956902416/pen/wvEPMvJ

**Comment by rsimon** [comment]
Interesting. Looks good, many thanks for the fix!
