### ISSUE TITLE
Error in editor position when customizing

### ISSUE THREAD

**Issue by ddankwerth** [recogito/recogito-client-core#33]
As per issue 19, i am following th example and when i add a widget using a widget object with function and some data, the widget opens in such a manner that its part hidden
Opens "above" and not "below"

**Comment by rsimon** [comment]
Sounds like a CSS issue. Do you have a screenshot and/or a code example?

**Comment by ddankwerth** [comment]
Argh .... I work in a bank , its impossible to even get to the issues page
Ill try to create an example on my personal machine a load it

Thanks, otherwise the customisation is really nice and simple api

בתאריך יום ג׳, 20 באוק׳ 2020, 12:25, מאת Rainer Simon ‏<
notifications@github.com>:

**Comment by ddankwerth** [comment]
Can be closed , i cant reproduce in a sample and i have worked around the issue
