### ISSUE TITLE
Moving selection not reflected in custom widget

### ISSUE THREAD

**Issue by ddankwerth** [recogito/recogito-client-core#34]
I have written a custom widget
In the widget i query for the target selection and get it (on creating i use toAnnotation ... )
After the widget opens, i drag the selection, i can see in the handler for 'changeSelectionTargrt' that the value changes, however, within the widget, the selector value is still the one where it was opened, also , is there a way to prevent moving the selector ?

**Comment by ddankwerth** [comment]
I want to clarify
In the widget i don't update the annotation , i want to get its current
selection ( for the purpose of OCR)
When i open the editor , the target selection is fine, when i drag the
selection, the widget is stuck with old values, thus, the OCR i do is done
on 'wrong' squere

בתאריך יום א׳, 1 בנוב׳ 2020, 10:30, מאת Rainer Simon ‏<
notifications@github.com>:

**Comment by rsimon** [comment]
There will probably be a change to the API for custom widgets at some point. But at the moment, it works the following way:

- The widget will get the annotation when the popup opens, but can only ever modify the bodies through the callback functions. - Annotorious handles updating of the target when the annotation is created. I.e. the `createAnnotation` event will include the correct selection coordinates. 

- Storing an annotation from inside the custom widget will likely lead to unwanted side effects. (Like not having the most recent target.) Even with custom widgets, you have to use the `createAnnotation` , `updateAnnotation`, `deleteAnnotation` events for lifecycle handling.

- There's currently no way to prevent moving the selection. That will probably come as some sort of additional editing option (like readOnly, but as an extra option).

**Comment by rsimon** [comment]
If you only want to get notified of the current selection, including when it changes, you can listen to the `changeSelectionTarget` event. This will be fired on every move, and hand in the current target as an argument.

I.e. you wouldn't need a custom editor widget at all for this.

If, however, you want to update some kind of custom UI element inside the editor popup in response to a moved selection, you could keep a reference to the element "outside" of the plugin and modify its content in response to `changeSelectionTarget`. Bit hacky, but should work.

**Comment by ddankwerth** [comment]
Hi ,

I need , within thw widget, to know the current selection, when moving or
changing the selection, the event indeed fores, but it seems to not get
updated for the copy inside the editor widget, , i can do tricks to
workaround that but seems wrong


בתאריך יום א׳, 1 בנוב׳ 2020, 12:40, מאת Rainer Simon ‏<
notifications@github.com>:

**Comment by rsimon** [comment]
That's right. The widget currently only gets re-rendred on changes to the annotation bodies, not the target. For now, hacking things from the outside, via the `onSelectionChange` event is your only option. At least until I get to revise/upgrade the widget API.

**Comment by rsimon** [comment]
An update on this one: the widgets now get an updated annotation when the user moves/resizes the selection.
