### ISSUE TITLE
annotation ID generation

### ISSUE THREAD

**Issue by falafeljan** [recogito/recogito-client-core#4]
would it be possible to make the generation of IDs for new annotations optional? currently, the selection component will assign a new UUID to an annotation upon creation:

https://github.com/recogito/recogito-client-core/blob/59b75174140dfd343f21e18dbcb2677e078c03d0/src/selection/Selection.js#L87-L95

the respective annotation server might want to provide an ID by itself and/or reject a previously generated ID. yet, providing an ID before sending it to an annotation server is _not wrong_ per se. the specification states (https://www.w3.org/TR/annotation-protocol/#create-a-new-annotation):
> Upon receipt of an Annotation, the server MAY assign IRIs to any resource or blank node in the Annotation, and MUST assign an IRI to the Annotation resource in the id property, even if it already has one provided.

i could imagine choosing the intended behaviour as a simple prop (`generateId`? `assignId`?) on the `TextAnnotator` component.

**Comment by rsimon** [comment]
Yes! I was thinking in a different direction though. When Recogito fires the `create` Event maybe there‘s a way for the host app to return a Promise of an ID. I.e. event gets fired, annotation gets POSTed to the server, server assigns ID, host app hands the ID to RecogitoJS. 

That might be stretching the event based API a bit too far though... (emitting an event shouldn‘t expect a return value, what about multiple registered event handlers etc.)

Otherwise, I‘d need to think whether there are any consequences to having ID-less annotations.

**Comment by rsimon** [comment]
Also see this: https://github.com/pelagios/recogito-text-js/issues/28

**Comment by rsimon** [comment]
Ok, checking the source code briefly. There‘s one piece of RecogitoJS that presently strictly needs IDs to function: relationship annotation. The relationship anchors record source and target by ID. Either we need to find a way to inject server-generated IDs, or think of another way to record relations.

**Comment by falafeljan** [comment]
recogito could stick to generating IDs and just explicitly mention this behavior in the documentation (if it doesn't right now? i didn't check). developers can then simply [remove the ID](https://github.com/hyperwell/test-environment/blob/012d42d2faf9e337a68c5ce7a4bd6c74f1edf0c2/src/App.svelte#L45-L59) if they desire as the annotation object should be a copy of the internal recogito annotation.

then, recogito could provide a function to replace the ID of an annotation. yet i don't know how to realize that with react props...

**Comment by rsimon** [comment]
Yes, the annotation handed to the outside world is a clone of the internal object. The annotations live in the [Highlighter](https://github.com/recogito/recogito-client-core/blob/master/src/highlighter/Highlighter.js), which isn‘t React. I.e. a hypothetical `updateId` method would be a conventional thing.

**Comment by falafeljan** [comment]
> a hypothetical updateId method would be a conventional thing.

absolutely. but i can't imagine how i as a developer could pass the information of updating an ID via the react API (that is, react props).

**Comment by rsimon** [comment]
That wouldn‘t be necessary. Only the editor popup is React. All that would be needed is an `updateId(annotationOrId, newId)` method on the Highlighter, which would get the affected annotation SPAN, and replace the annotation. No React involved.

**Comment by rsimon** [comment]
The only danger would be that the Editor needs to be closed. Because on __OK__, it would try to replace the existing annotation in the Highlighter, but then wouldn‘t find it anymore. But that can be forced, of course. (Just deselect before updating.)

**Comment by rsimon** [comment]
Re your edit: yes that was what I was thinking of. But I‘m not sure I can even get my hands on the return value of the event handler (I‘m using `tiny-emitter` for events). That’s something we can find out though of course.

**Comment by falafeljan** [comment]
looks like the module doesn't support retrieval of return values of `emit()`. admittedly, supporting that would sound like an odd API to me.

alternatively, we could just pass a callback function as a parameter to the `createAnnotation` event:

```js
r.on('createAnnotation', async (annotation, updateId) => {
  const newId = await server.createAnnotation(annotation)
  updateId(annotation.id, newId)
})
```

**Comment by rsimon** [comment]
I like this! Will add this next (but was too busy today with [another thing I wanted to try out](https://github.com/recogito/annotorious-openseadragon).

I'll add an `overrideId(annotationOrId, newId)` method to the Highlighter, and will then extend the `createAnnotation` event exactly like you say. That way, it's also possible for people to use either `async` `await` or the Promise-based syntax, e.g.

```javascript
r.on('createAnnotation', (annotation, overrideId) => {
  axios.post('/annotation-server').then(response => overrideId(annotation, response.data));
});
```
