### ISSUE TITLE
Re-design widget API

### ISSUE THREAD

**Issue by rsimon** [recogito/recogito-client-core#42]
The current widgets follow React's pattern of controlled inputs, mapping each widget to an annotation body, and keeping everything in sync as the user types. That's turning out to be more of a hindrance, especially in cases where widgets reflect content that's technically not part of the annotation yet (a new reply, or a new tag being written - which is currently covered by a workaround.)

Redesign the API in a more conventional, non-controlled way.

**Comment by rsimon** [comment]
Rethought this & the API is actually quite good in the immutable Rect-style way. Existing problems (like https://github.com/recogito/recogito-client-core/issues/37) were caused by my bad implementation rather than anything else. I.e. the API won't change (much), I cleaned up various bits and pieces in the implementation instead.

**Comment by rsimon** [comment]
P.S.: in order to allow modification of "top-level" attributes on the annotation (rather than the body), I propose a new callback method in the Editor component: `setProperty`. In a similar way to `addBody`, `removeBody` and `updateBody`, this method could modify the current annotation in a controlled way.

Usage example:

```js
props.setProperty('motivation', 'linking');
```

**Comment by dnoneill** [comment]
@rsimon Was this ever integrated?

**Comment by rsimon** [comment]
Yes, the .setProperty method is available in the `args` object that gets handed to the widget function.

**Comment by dnoneill** [comment]
Thanks!
