### ISSUE TITLE
Autofocus for the textArea

### ISSUE THREAD

**Issue by ufuk23** [recogito/recogito-client-core#61]
Could you please add autofocus to the Editor Add Comment Text Area (r6o-editable-text)? Otherwise, the user should click the text area to type some comment after the drawing. I think it can be a useful feature, and it works after the editor dialog is shown.

![image](https://user-images.githubusercontent.com/8513827/122778876-0b46c400-d2b6-11eb-9adc-03a15e7dbf8b.png)

Best Regards.

**Comment by rsimon** [comment]
I just moved the issue over to the`recogito-client-core` repo. (That's where all the code for the editor is.) Good suggestion. 

Technically, people can configure the editor in different ways, so I guess it's best to auto-focus the first widget. I'll put that on my list for one of the next releases :-)

**Comment by ufuk23** [comment]
Thanks a bunch. Which element and event are most proper to do it?

**Comment by rsimon** [comment]
The Comment/Reply field uses the `TextArea` component here:
https://github.com/recogito/recogito-client-core/blob/main/src/editor/widgets/comment/TextEntryField.jsx

**Comment by rsimon** [comment]
The editor now sets delegates focus to the first widget in the list. (In the default setting, that's the `CommentWidget`.) Potentially, there's now also a mechanism to configure from the outside which widget should get initial focus, but that's not fully implemented yet.

**Comment by ufuk23** [comment]
Thank you, that's another useful feature
