### ISSUE TITLE
How to call the ok button from a widget?

### ISSUE THREAD

**Issue by Apeli** [recogito/recogito-client-core#66]
Is there a way to add an annotation / click the "OK" button programmatically from inside a Widget?

Something like this?
https://recogito.github.io/annotorious/api-docs/annotorious/#saveselected

**Comment by rsimon** [comment]
I re-read the code and, no, unfortunately that's also not possible - at least not without loosing annotation bodies like in issue #65. Frankly, the current React implementation of the editor solves as many problems as it causes. I need to re-organize that bit somewhat to provide more possibilites for widget extensions.

However: I'm on the case. Expect updates for this and #65 soon!

**Comment by rsimon** [comment]
For posterity (this will go into the docs later!): all widget callback functions now have an optional additional argument `saveImmediately`. Set this to `true` to save the annotation and close the editor immediately after applying the change:

```js
args.onAppendBody(body, true);
args.onRemoveBody(body, true);
args.onUpdateBody(previousBody, updatedBody, true);
args.onUpsertBody(optPrevious, updatedBody, true);
args.onBatchModify(diffs, true);
```
