### ISSUE TITLE
Showing comment near the drawing

### ISSUE THREAD

**Issue by ufuk23** [recogito/recogito-client-core#67]
We need to show comments (max 40 chars) near the drawing (bottom or top). How could I show the comments while drawings appear on the picture?

**Comment by rsimon** [comment]
Did you look at the [Shape Labels plugin](https://github.com/recogito/recogito-client-plugins/tree/main/packages/annotorious-shape-labels)? The code should be fairly easy to adapt, so that it doesn't show the first tag, but instead the first 40 characters of the comment.

**Comment by ufuk23** [comment]
Wow!!! That looks good, actually not good it perfectly fits my need, you are awesome dude !!! You can not think about how you save my day :) :) 👍
