### ISSUE TITLE
How to save the annotation without showing the editor dialog

### ISSUE THREAD

**Issue by ufuk23** [recogito/recogito-client-core#68]
How could I save the annotation without showing the editor dialog? We need the user to draw shapes and save them without the editor dialog and comment etc. After the user draws the shape we need to add a custom tag to the annotation automatically. I think we can do that via 'createAnnotation' event of annotorious,  so we just need to save annotation without showing the editor dialog.

**Comment by rsimon** [comment]
https://recogito.github.io/guides/headless-mode/

**Comment by ufuk23** [comment]
you blessed man !!!
👍
