### ISSUE TITLE
Initial editor position on long pages

### ISSUE THREAD

**Issue by Apeli** [recogito/recogito-client-core#69]
I noticed that on longer pages (with content longer than what fits in the viewport), when creating a new selection/annotation the page scrolls to the bottom of the viewport before showing the editor. You can reproduce by adding more content to the public/index.html #content div.

In setPosition() the selectedEl is a Range which seems to have a messed up .getBoundingClientRect(). Do you know if this could be avoided with some css definitions on the parent etc?

**Comment by rsimon** [comment]
Interesting... thanks for reporting. Looks like this is a regression introduced with the latest version (RecogitoJS 1.3.0)... There weren't any changes to `setPosition` I think, only the editor refactoring to support the new body update features (batch update, close immediately). I.e. must be a side effect of these architectural changes. I'll investigate.
