### ISSUE TITLE
locale config option not working in Annotorious OSD

### ISSUE THREAD

**Issue by enekonieto** [recogito/recogito-client-core#71]
Thank you for this amazing project!

    const config = {
      widgets: [
        'COMMENT'
      ],
      locale: 'de',
    };

    const anno = Annotorious(viewer, config);

Previous code gives `Unsupported locale 'de'. Falling back to default en.`. Same result with `en` and `es`.

Using annotorious-openseadragon 2.5.2

**Comment by rsimon** [comment]
Looks like a regression bug... Thanks for reporting, I'll look into it!

**Comment by rsimon** [comment]
Fixed the root cause in commit 9761a733a56cd6d930daa88f32dbf1be1b560d66
