### ISSUE TITLE
Custom Translations

### ISSUE THREAD

**Issue by dnoneill** [recogito/recogito-client-core#78]
I want to change the "Ok" button to read "Save." I was wondering if there was a way to custom load that into Annotorious, I figured that might be possible with a custom translation, but I wasn't able to find documentation on how to do that or if it was possible.

**Comment by rsimon** [comment]
Hi @dnoneill, you can override (or partially override) the labels by adding your own `messages` dictionary as an init paramter:
https://recogito.github.io/annotorious/api-docs/annotorious/#initialization

Something like this should work:

```js
Annotorious.init({
  messages: { "Ok": "Save" }
});
```

**Comment by dnoneill** [comment]
I knew there had to be something. Thanks so much.
