### ISSUE TITLE
Allow for dictionary vocabularies for tags widget

### ISSUE THREAD

**Issue by dnoneill** [recogito/recogito-client-core#79]
@rsimon if you could point me to towards where this would happen I can probably code it. I can build this in my app but I think it might be better if it was built into Annotorious.

The idea is you would be able to feed a dictionary like this:{ "person": "https://www.wikidata.org/wiki/Q215627",
 "date of birth": "https://www.wikidata.org/wiki/Q2389905"} into the tags dictionary. Then the user can type in date of birth and choose it from the tags vocabulary. What would display is the free text, but the url for Wikidata would be written to the final annotation.

**Comment by rsimon** [comment]
This is definitely a case for a widget plugin, not a core feature. Basic instructions on developing widgets are here:

https://recogito.github.io/guides/editor-widgets/

and

https://recogito.github.io/guides/example-react-widget/

(The more complex widgets get, the easier it is to build them in React.)

The docs for widget development are still a bit incomplete. I can point you to a bigger, more real-world example when I'm back from vacation in ~2 weeks.

**Comment by dnoneill** [comment]
Thanks.

**Comment by rsimon** [comment]
In any case: the class to modify would be `TagWidget` (somewhere in editor/widgets). And I guess you'd need to produce bodies that have purpose = tagging, value = URI, label = UI label.

**Comment by rsimon** [comment]
Hi @dnoneill, I had a few chats recently & it looks like controlled vocabularies with terms + URIs are needed for one of my paid projects (using AnnotoriousOSD). I evaluated things, and it's probably more painless to just extend the default tag widget and make this a core feature after all. I expect I can work on this next week.

**Comment by rsimon** [comment]
I just added support for vocabularies with label + URI in [this commit](https://github.com/recogito/recogito-client-core/commit/e95c98391c9767dc47a7b4daff64846e925c9c4d). The API looks just slightly different. Each vocabulary item can be either a string, or an object with `label` and `uri` property.

```js
var r = Recogito.init({
  content: 'content', // Element id or DOM node to attach to
  widgets: [{ 
    widget: 'TAG',
    vocabulary: [ 
      { label: 'Place', uri: 'http://www.example.com/ontology/place' },
      { label: 'Person', uri: 'http://www.example.com/ontology/place' }, 
      { label: 'Event', uri: 'http://www.example.com/ontology/event' },
      { label: 'Organization', uri: 'http://www.example.com/ontology/organization' },
      { label: 'Animal', uri: 'http://www.example.com/ontology/animal' }
    ] 
  }]
});
```

You could even mix labels vs. ontology terms if you wanted.

```js
var r = Recogito.init({
  content: 'content', // Element id or DOM node to attach to
  widgets: [{ 
    widget: 'TAG',
    vocabulary: [ 
      { label: 'Place', uri: 'http://www.example.com/ontology/place' },
      'Person', 
      { label: 'Event', uri: 'http://www.example.com/ontology/event' },
    ] 
  }]
});
```

The implementation is a bit of a hack on top of the [Downshift autocomplete component](https://www.downshift-js.com/). I've never been happy with that... seemed a time-saver when I first built the tag widget.. But there's definitely no way around kicking it out and replacing it with (probably) a hand-crafted solution in the long run. Anyways... that's just a bit of ranting though. The vocabulary API won't be affected by that.

**Comment by dnoneill** [comment]
@rsimon Thanks so much.
